version: '3'
services:
  container:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    ports:
      - 3000:3000
    volumes:
      - /app/node_modules
      # - ./:/app
      - ./src:/app/src
      - ./nodemon.json:/app/nodemon.json
    networks:
      - node-net
    # depends_on:
    #   - mongo
    env_file:
    - ./.env
  # mongo:
  #   image: mongo
  #   ports:
  #     - 27018:27017
  #   volumes:
  #     - mongodb:/data/db
  #   networks:
  #     - node-net
# volumes:
#  mongodb:

networks:
  node-net:
    driver: bridge